services:
  web:
    build: .
    container_name: consultorio_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
