services:
  web:
    build: .
    container_name: consultorio_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_USER: root
      MYSQL_PASSWORD: 235689
      MYSQL_DATABASE: consultorio
